-- liquibase formatted sql

-- changeset V:2
CREATE TABLE bid (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bidder_name VARCHAR(64) NOT NULL,
    bid_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    lot_id INTEGER NOT NULL REFERENCES lot(id)
);